# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppOftamologia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppOftamologia

   pod 'Firebase'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'Doppelganger'
   pod 'CarbonKit'
   pod 'ScrollableGraphView'
   pod 'STPopup'
   pod 'DZNEmptyDataSet'
   pod 'MBProgressHUD', '~> 1.1.0'
   pod 'SCLAlertView'
   pod 'ImageSlideshow', '~> 1.4'
   pod 'INSPhotoGallery'
   pod 'UPCarouselFlowLayout'
   pod 'ZoomTransition'
   pod 'MGSwipeTableCell'
   pod 'UICircularProgressRing'
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'paper-onboarding'


end
